name: Shell commands
on: [push]
jobs:
  run-shell-command:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-20.04]
    env:
      MY_KEY: ${{ vars.MY_KEY }} 
    steps:
      - name: echo a string
        run: echo "$MY_KEY"
      - name: multiline script
        run: |
          python3 -V
          touch my_file_with_workflow.py
          ls -l