name: Shell commands
on: [push]
jobs:
  run-shell-command:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    environment: env
    env:
      MY_KEY: ${{ secrets.MY_KEY }} 
    steps:
      - name: echo a string
        run: |
          echo "$MY_KEY" | sed 's/./& /g'
      - name: multiline script
        run: |
          python3 -V
          touch my_file_with_workflow.py
          ls -l